version: "3.8"
services:
  gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file: ./api-gateway/.env
    ports: 
      - "9000:9000"
    volumes:
      - './api-gateway:/usr/src/gateway'
      - /usr/src/gateway/node_modules
    networks:
      - microservices-network

networks:
  microservices-network:
