version: "3.8"
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file: ./api-gateway/.env
    ports: 
      - "9000:3000"
    volumes:
      - './api-gateway:/usr/src/gateway'
      - /usr/src/gateway/node_modules
    networks:
      - microservices-network
    depends_on:
      - user-service
      - post-service
      - comment-service
  comment-service:
    container_name: comment-service
    build:
      context: ./microservices/comment-service
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    networks:
      - microservices-network

  post-service:
    container_name: post-service
    build:
      context: ./microservices/post-service
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    networks:
      - microservices-network

  user-service:
    container_name: user-service
    build:
      context: ./microservices/user-service
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    networks:
      - microservices-network

networks:
  microservices-network:
