name: Pulumi Development Container Builds & Deploys

on:
  push:
    branches:
      - dev

env:
  CONTAINER_TAG: ${{ github.run_number }}


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Create docker-compose env file
        run: |
          touch config.env
          echo "${{ env.CONTAINER_TAG }}" >> config.env
          cat config.env

      - name: Build and run containers
        run: docker-compose up --env-file config.env --build

      - name: Push containers
        run: docker-compose push
